[project]
name = "tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kokoro>=0.7.16",
    "numpy>=1.26.4",
    "pip>=25.0.1",
    "soundfile>=0.13.1",
]

[project.entry-points.console_scripts]
tts = "tts:main"
